# Experiment
output_path: 'workspace' # output dir
save: True # Saving intermediate files
dataset: "redwood" # redwood, pcn, scannet
device: "cuda"

# Depth Prompting
coords_scale: 0.5
distance: 1.6 # 1.6 cameras distance
fovy: 49.1 # cameras fov
point_size: 1 #2
mask_pixel_rate: 3
downsample_num: 10000
removal_radius: 10000 # hidden point removal radius
camera_distribution: fibonacci_sphere
cam_res: 256  # 256 rendering res
view_num: 1024 # if view_num=6, is orthogonal camera
camera_base: 'kaolin'  # blender, kaolin

# inpaint
res: 256 # inpainting resolution
edge_point_size: 2
generate_res: 512

# crop and rescale
rescale: True  #
padding: 0.15
mask_ratio_thresh: 0.82 # 0.82 for everything else, 0.5 for diffPIR

inpainter: 'cv2' # [‘flux’, 'DDNM'，cv2]
rembg_model: 'RMBG' # ['rembg', 'RMBG']
control_model: "qwen" # ['controlnet', 'adapter', flux, qwen]

generative_model: "instantmesh" # ['instantmesh', 'hunyuan2.0', sf3d, trellis]
